name: Test
version: ${project.version}
main: me.nullcat.test.Test
api-version: 1.13
authors: [Me]
description: Test
commands:
  mapChunk:
    description: Force Map The Chunk a Player is in
    usage: /<command>
